websearch:
  use_rag: true
  rag_config_path: examples/rag/config.yaml
  use_summary: true
  n_subqueries : 2
  input_file: examples/rag/output.json
  input_queries: examples/rag/queries.jsonl
  output_file: examples/websearchRAG/enhanced_results_trial.json
  n_loops: 2
  max_searches: 5
  search_provider: duckduckgo
  max_retries: 3
  max_context_tokens: 2048
  fast_tokenizer: false
  mode: local
  llm_config:
    llm_name: OpenMeditron/meditron3-8b # Qwen/Qwen2-0.5B 
    max_new_tokens: 1200
