data_path: /mnt/mlo/scratch/homes/polydoc/datasets/who_guidelines/processed/extraction_results_47k/merged/merged_results.jsonl
pipeline:
  pp_modules:
    - type: chunker
      args:
        chunking_strategy: semantic
        table_handling: single_row
    - type: lang_detector
  output:
    output_path: /mnt/mlo/scratch/homes/polydoc/datasets/who_guidelines/processed/extraction_results_47k/chunk-semantic
    save_each_step: True